### ISSUE TITLE
Pyperclip does not persist if called from script

### ISSUE THREAD

**Issue by Sheldan** [asweigart/pyperclip#61]
I want to store something into the clipboard via a python script.
It's basically just `pyperclip.copy('text')`. I'm using Fedora 21 with AwesomeWM. I read [here](http://stackoverflow.com/questions/11063458/python-script-to-copy-text-to-clipboard#comment54819131_25476462) that a clipboard manager is needed to store it permanent in the clipboard. I installed parcellite. It now works, if I use it in an terminal, via
```
$python
$>>> import pyperclip
$>>> pyperclip.copy('teststring')
```
BUT if I do the exact same thing in an script
```
import pyperclip
pyperclip.copy('teststring')
```
and execute this script with `python filename`.
It won't get stored in the clipboard.

Any ideas on where the error may happen?

**Comment by seanpianka** [comment]
I believe I am experiencing a similar issue in my project. I am copying text from a response object's JSON to the system clipboard. But, it seems that after copying, the clipboard is "locked" in a way that copying OR pasting does not work (right-click shows the options as grayed out, unclickable) and will only work once the running script is closed/ended from the terminal window.

The structure of my program is as follows:
 * Tkinter GUI with a button to call a function that involves the copying.
 * Within the called function, use Subprocess' POpen function to use a command from the command-line in the script.
 * Then, use requests to make a POST request with data returned from the shell command. 
 * From the response object's, copy a string of text from one key-value pair and attempt to copy that to the system clipboard using Pyperclip. 
 * Then, return from the function back to the Tkinter (which is running in a main loop.

I am not sure why the issue is happening, but I will keep working to try and figure it out on my own. However, any outside help would certainly be appreciated!

**Comment by Achifaifa** [comment]
I'm afraid I'm having a similar issue. I've tested this using `pyperclip.copy("test")` in an ipython console. if I try to paste somewhere else, the text doesn't appear until I close the console.

Any clues about what's happening here? Feels weird.

**Comment by pta2002** [comment]
I've got the same issue, Arch Linux with python 3.5.2 if that matters

**Comment by firewater** [comment]
I am also experiencing the same scenario as @Sheldan. Has anyone resolved the problem using Pyperclip?

**Comment by kraamis** [comment]
Confurm

Debian Testing, Python 3.6.6

**Comment by jcesarprog** [comment]
here too..ubuntu 18 LTS python 3.7

**Comment by AbhishekCCT** [comment]
python 3.6.2
Ubuntu 18.04.1 LTS


If I copy some text from the terminal using pyperclip.copy(), it is smooth to paste it with ctrl+v and/or with pyperclip.paste() but when I copy something from the script written through a text editor(in my case sublime , atom) there is nothing on the clipboard. I am not able to extract it, neither pyperclip.paste(), nor ctrl + v is working.

**Comment by yangyangwithgnu** [comment]
guys, u need xclip n xsel: 

sudo apt-get install xclip xsel

**Comment by soulslicer** [comment]
same issue. this just happened recently

**Comment by mjdude** [comment]
I have the same issue, python 3.7.0 on Ubuntu 18.04. ANyone know the underlying for this or idea on how to start debugging.

**Comment by samuelkister** [comment]
> guys, u need xclip n xsel:
> 
> sudo apt-get install xclip xsel

solved this issue by me (Ubuntu 18.10, running script in PyCharm)

**Comment by allosh119** [comment]
> guys, u need xclip n xsel:
> 
> sudo apt-get install xclip xsel

Fixed the issue. 
thanks

**Comment by MShafquat** [comment]
> guys, u need xclip n xsel:
> 
> sudo apt-get install xclip xsel

Thanks. But does it mean my program would not run on a PC where xclip and xsel are not installed?

**Comment by Dataphil** [comment]
I'm still having the issue, even after installing xclip and/or xsel. Using Kubuntu 18.04 LTS.

**Comment by AtufaShireen** [comment]
i am also having the same problem , the pyperclip works in editor but not in cmd | how do we solve it on windows?

**Comment by ParkerPy** [comment]
Everyone see yangyangwithgnu's comment above to resolve this issue.
https://github.com/asweigart/pyperclip/issues/61#issuecomment-415934948

**Comment by kledijenicerri** [comment]
try 
import pyperclip
pyperclip.copy('test')
print(pyperclip.paste())

**Comment by YuriiShp** [comment]
solved for Ubuntu 20.04 & Python 3.8.  I just activated python virtual environment

open terminal and type:
~$: cd path/to/project
~/path/to/project$: source venv/bin/activate
(venv)~/path/to/project$: python3 script.py
and it works

to avoid printing routine you can create .sh file like following:
~$: gedit runme.sh

in gedit file type:
        #!/bin/bash
        cd path/to/project
        source venv/bin/activate
        python3 script.py
save and close

open terminal and type:
~$: chmod +x runme.sh   # only once
~$: ./runme.sh

and that's it next time just type in terminal the last command

**Comment by PedroDmaster** [comment]
> guys, u need xclip n xsel:
> 
> sudo apt-get install xclip xsel

worked for me (pop_OS , vscode)

**Comment by SmartManoj** [comment]
For Arch based, 
`sudo yay -S xclip xsel`
